import { Medicine } from './types';

// サンプルデータ（実際は API から取得することが多い）
export const allMedicines: Medicine[] = [
  {
    id: 1,
    name: 'アセトアミノフェン錠',
    ingredients: 'アセトアミノフェン',
    category: '解熱鎮痛剤',
    effect: '発熱、頭痛の緩和',
  },
  {
    id: 2,
    name: 'ロキソプロフェンナトリウム',
    ingredients: 'ロキソプロフェン',
    category: '解熱鎮痛剤',
    effect: '炎症や痛みを抑える',
  },
  {
    id: 3,
    name: 'アレグラ錠',
    ingredients: 'フェキソフェナジン',
    category: '抗アレルギー薬',
    effect: '花粉症、鼻炎の症状緩和',
  },
  {
    id: 4,
    name: 'ムコダイン錠',
    ingredients: 'L-カルボシステイン',
    category: '去たん薬',
    effect: '痰を出しやすくする',
  },
  {
    id: 5,
    name: 'ガスター10',
    ingredients: 'ファモチジン',
    category: '胃腸薬',
    effect: '胃酸の分泌を抑える',
  },
  {
    id: 6,
    name: 'メジコン錠',
    ingredients: 'デキストロメトルファン',
    category: '鎮咳薬',
    effect: '咳を鎮める',
  },
  {
    id: 7,
    name: 'クラリチン',
    ingredients: 'ロラタジン',
    category: '抗アレルギー薬',
    effect: 'アレルギー性鼻炎',
  },
  {
    id: 8,
    name: 'バファリンA',
    ingredients: 'アスピリン',
    category: '解熱鎮痛剤',
    effect: '痛み、熱を抑える',
  },
  {
    id: 9,
    name: 'パブロンゴールド',
    ingredients: 'グアイフェネシン',
    category: '総合風邪薬',
    effect: '風邪の諸症状緩和',
  },
  {
    id: 10,
    name: 'ジルテック',
    ingredients: 'セチリジン',
    category: '抗アレルギー薬',
    effect: 'かゆみ、鼻炎の緩和',
  },
  {
    id: 11,
    name: 'ビオフェルミン',
    ingredients: 'ビフィズス菌',
    category: '整腸薬',
    effect: '便通を整える',
  },
  {
    id: 12,
    name: 'マーズレン',
    ingredients: 'アズレン',
    category: '胃粘膜保護薬',
    effect: '胃の粘膜を保護する',
  },
  {
    id: 13,
    name: 'カロナール',
    ingredients: 'アセトアミノフェン',
    category: '解熱鎮痛剤',
    effect: '穏やかな解熱鎮痛',
  },
  {
    id: 14,
    name: 'アドエア',
    ingredients: 'サルメテロール',
    category: '喘息治療薬',
    effect: '気管支を広げる',
  },
  {
    id: 15,
    name: 'シングレア',
    ingredients: 'モンテルカスト',
    category: '喘息・鼻炎薬',
    effect: '気道の炎症を抑える',
  },
  {
    id: 16,
    name: 'クラリス',
    ingredients: 'クラリスロマイシン',
    category: '抗生物質',
    effect: '細菌の感染を抑える',
  },
  {
    id: 17,
    name: 'メイアクト',
    ingredients: 'セフジトレン',
    category: '抗生物質',
    effect: '広い範囲の細菌感染',
  },
  {
    id: 18,
    name: 'アムロジン',
    ingredients: 'アムロジピン',
    category: '血圧降下剤',
    effect: '血圧を下げる',
  },
  {
    id: 19,
    name: 'リピトール',
    ingredients: 'アトルバスタチン',
    category: '脂質異常症薬',
    effect: 'コレステロールを下げる',
  },
  {
    id: 20,
    name: 'タミフル',
    ingredients: 'オセルタミビル',
    category: '抗インフルエンザ薬',
    effect: 'ウイルスの増殖を抑える',
  },
  {
    id: 21,
    name: 'ゾフルーザ',
    ingredients: 'バロキサビル',
    category: '抗インフルエンザ薬',
    effect: 'ウイルスの増殖を抑える',
  },
  {
    id: 22,
    name: 'アレロック',
    ingredients: 'オロパタジン',
    category: '抗アレルギー薬',
    effect: '強いかゆみ、鼻炎の緩和',
  },
  {
    id: 23,
    name: 'セルベックス',
    ingredients: 'テプレノン',
    category: '胃薬',
    effect: '胃粘膜を保護する',
  },
  {
    id: 24,
    name: 'セルニルトン',
    ingredients: '植物花粉エキス',
    category: '前立腺肥大症薬',
    effect: '排尿の悩みの緩和',
  },
  {
    id: 25,
    name: 'トラネキサム酸',
    ingredients: 'トラネキサム酸',
    category: '止血・抗炎症',
    effect: '喉の痛み、出血を抑える',
  },
  {
    id: 26,
    name: 'ナゾネックス',
    ingredients: 'モメタゾン',
    category: '点鼻ステロイド',
    effect: '鼻の炎症を抑える',
  },
  {
    id: 27,
    name: 'リンデロンV',
    ingredients: 'ベタメタゾン',
    category: 'ステロイド外用薬',
    effect: '皮膚の炎症を抑える',
  },
  {
    id: 28,
    name: 'ヒルドイド',
    ingredients: 'ヘパリン類似物質',
    category: '保湿剤',
    effect: '皮膚の乾燥を防ぐ',
  },
  {
    id: 29,
    name: 'アクトス',
    ingredients: 'ピオグリタゾン',
    category: '糖尿病用薬',
    effect: '血糖値を下げる',
  },
  {
    id: 30,
    name: 'ラシックス',
    ingredients: 'フロセミド',
    category: '利尿剤',
    effect: 'むくみを改善する',
  },
];
